version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    networks:
      - my_network
    ports:
      - "6333:6333"
    # environment:
    #   QDRANT__SERVICE__HOST: "0.0.0.0"
    #   QDRANT__SERVICE__PORT: 6333
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "8000:8000"
      - "8501:8501"
    depends_on:
      - qdrant
    environment:
      PYTHONPATH: "/app/"

networks:
  my_network:
